import type { LucideIcon } from "lucide-react";
import {
  BookOpen,
  Building2,
  Code2,
  Facebook,
  FileText,
  Globe,
  GraduationCap,
  HeartHandshake,
  Instagram,
  Landmark,
  Linkedin,
  Megaphone,
  MessageCircle,
  Music2,
  PenTool,
  Podcast,
  Presentation,
  ShoppingBag,
  Sparkles,
  Timer,
  Twitter,
  Users,
  Wallet,
  Youtube,
} from "lucide-react";

export type HubKey = "IPN" | "IGC" | "IFR" | "ISR";

export type SocialLink = { label: string; url: string; icon: LucideIcon };

export type ServiceFaq = { question: string; answer: string };

export type GateService = {
  slug: string;
  name: string;
  icon: LucideIcon;
  headline: string;
  short: string;
  value: string;
  what: string[];
  audience: string[];
  benefits: string[];
  process: string[];
  pricing: string;
  faqs: ServiceFaq[];
  relatedCategories: string[];
  relatedTopics: string[];
  contentTypes: string[];
  trust?: string[];
};

export type GateHub = {
  key: HubKey;
  slug: string;
  name: string;
  tagline: string;
  focus: string;
  identity: string;
  website: string;
  whatsapp: string;
  categories: string[];
  services: GateService[];
  socials: SocialLink[];
};

const WHATSAPP = "https://wa.link/f44l0k";
const DEFAULT_PROCESS = ["Enquire", "Discuss Requirements", "Receive Proposal", "Confirm Scope", "Delivery & Follow-up"];
const CONTENT_TYPES = ["Books", "Infographics", "Podcasts", "Research Reports"];

const defaultFaqs = (service: string): ServiceFaq[] => [
  {
    question: `How do I enquire about ${service.toLowerCase()}?`,
    answer: `Use the WhatsApp enquiry button on this page to share your requirement. The Gate team will confirm scope, timing and pricing with you directly.`,
  },
  {
    question: `Is pricing for ${service.toLowerCase()} standard or customised?`,
    answer: `Most ${service.toLowerCase()} engagements use customised pricing based on scope and format. You will receive a clear proposal after discussing your requirements.`,
  },
  {
    question: "How is delivery handled?",
    answer: "After confirming the scope, the Gate team delivers through a structured process with defined milestones and follow-up support where applicable.",
  },
];

export const hubs: GateHub[] = [
  {
    key: "IPN",
    slug: "ipn",
    name: "International Public Network",
    tagline: "For Planet, People, Progress & Policies.",
    focus: "Public affairs, journalism, global affairs and society.",
    identity:
      "IPN is the public affairs arm of Gate, covering world politics, policy, environment, law, science, health, education, security and culture through books, podcasts, infographics and research reports.",
    website: "https://www.drzaydhaji.com",
    whatsapp: WHATSAPP,
    categories: [
      "World",
      "Politics & Governance",
      "Business & Economy",
      "Society",
      "Environment & Climate",
      "Law & Justice",
      "Science & Technology",
      "Health",
      "Education",
      "Security & Defence",
      "Culture & Lifestyle",
      "Sports",
    ],
    socials: [
      { label: "Website", url: "https://www.drzaydhaji.com", icon: Globe },
      { label: "YouTube", url: "https://www.youtube.com/channel/UCmOSNgWPPQqYEaeGcdXBURA", icon: Youtube },
      { label: "Spotify", url: "https://open.spotify.com/show/033VCxjOKlNfHBM1wceTwZ?si=b7f6592b89f8447e", icon: Music2 },
      { label: "Apple Podcasts", url: "https://podcasts.apple.com/us/podcast/ipn-|-internattional-public-network/id6794651434", icon: Podcast },
      { label: "Instagram", url: "https://www.instagram.com/ipg.gate", icon: Instagram },
      { label: "Facebook", url: "https://www.facebook.com/ipn.gate/", icon: Facebook },
      { label: "LinkedIn", url: "https://www.linkedin.com/company/ipngate/", icon: Linkedin },
      { label: "X", url: "https://www.x.com/ipngate", icon: Twitter },
      { label: "WhatsApp Community", url: "https://chat.whatsapp.com/KFy7LSrHTRN8el6mB8Nnrk", icon: MessageCircle },
      { label: "WhatsApp Channel", url: "https://whatsapp.com/channel/0029VbDCIAdL2ATxOkziUr19", icon: MessageCircle },
    ],
    services: [
      {
        slug: "advertising",
        name: "Advertising",
        icon: Megaphone,
        headline: "Reach audiences who care about the world.",
        short: "Branded placements across IPN's global public affairs channels.",
        value: "Editorial-context reach for global public affairs brands.",
        what: [
          "IPN Advertising places your organisation in front of an engaged international audience interested in world politics, policy, science and society. Campaigns are planned around editorial context rather than interruption.",
          "From sponsored podcast and report placements to featured digital positioning, every campaign is designed around IPN's editorial standards so that your message appears alongside credible public affairs content.",
          "You receive clear reporting on reach and engagement, with placements that can be planned per campaign, per series or across the IPN channel network.",
        ],
        audience: ["Policy-minded professionals", "Government and public bodies", "Academic institutions", "Purpose-driven brands", "International organisations"],
        benefits: ["Contextual placements aligned with IPN content", "Sponsored podcast and report positioning", "Editorial-driven campaign planning", "Transparent reporting on reach", "Access to IPN's engaged global audience"],
        process: DEFAULT_PROCESS,
        pricing: "Customised pricing",
        faqs: defaultFaqs("advertising"),
        relatedCategories: ["World", "Business & Economy", "Science & Technology"],
        relatedTopics: ["Global", "United Nations", "Public Affairs"],
        contentTypes: CONTENT_TYPES,
      },
      {
        slug: "api-access",
        name: "API Access",
        icon: Code2,
        headline: "Build on a trusted source of global knowledge.",
        short: "Structured IPN content feeds and metadata for products and platforms.",
        value: "Structured, reliable Gate content for your platform.",
        what: [
          "IPN API Access lets developers and institutions integrate curated IPN data, categories and content feeds into their own products.",
          "It is designed for research platforms, media applications and analytics teams that need structured, reliable public affairs content at scale, with secure credentials, documentation and usage analytics.",
        ],
        audience: ["Product developers", "Research teams", "Media platforms", "Analytics organisations", "Startups and enterprises"],
        benefits: ["Structured IPN content feeds", "Category and tag metadata", "Secure API credentials", "Documentation and support", "Usage analytics for API calls"],
        process: DEFAULT_PROCESS,
        pricing: "Customised pricing",
        faqs: defaultFaqs("API access"),
        relatedCategories: ["Science & Technology", "Business & Economy", "World"],
        relatedTopics: ["Global", "Digital", "Public Affairs"],
        contentTypes: CONTENT_TYPES,
      },
      {
        slug: "events",
        name: "Events",
        icon: Presentation,
        headline: "Bring people together around the issues that matter.",
        short: "Live and digital convenings on international affairs, policy and society.",
        value: "Informed conversations on the issues that shape the world.",
        what: [
          "IPN Events organise live and digital convenings on international affairs, policy and society, from roundtables to public lectures.",
          "Each event is designed to create informed conversation among practitioners, scholars and engaged citizens, with follow-up resources for attendees.",
        ],
        audience: ["Public affairs professionals", "Academics and researchers", "Journalists", "Policy institutions", "Community leaders"],
        benefits: ["Live and online event formats", "Themed around current global issues", "Speaker and panel curation", "Networking and follow-up resources", "Media coverage opportunities"],
        process: DEFAULT_PROCESS,
        pricing: "Customised pricing",
        faqs: defaultFaqs("events"),
        relatedCategories: ["World", "Politics & Governance", "Society"],
        relatedTopics: ["Global", "Governance", "Public Affairs"],
        contentTypes: CONTENT_TYPES,
      },
      {
        slug: "journalism-workshops",
        name: "Journalism Live Online/Offline Workshops",
        icon: PenTool,
        headline: "Learn the craft of journalism from practice, not theory.",
        short: "Hands-on reporting, writing, fact-checking and responsible storytelling.",
        value: "Practical editorial craft from working standards.",
        what: [
          "IPN Journalism Workshops cover reporting, writing, fact-checking and responsible storytelling through practical exercises and real-world case studies.",
          "Sessions are delivered live online and in person, guided by working editorial standards, with direct feedback from experienced editors.",
        ],
        audience: ["Aspiring journalists", "Early-career reporters", "Student media teams", "Communications professionals", "Educators"],
        benefits: ["Practical reporting exercises", "Writing and fact-checking frameworks", "Live feedback from experienced editors", "Online and offline formats", "Certificate of participation"],
        process: ["Enquire", "Choose Format", "Receive Curriculum", "Attend Sessions", "Certificate & Follow-up"],
        pricing: "Customised pricing",
        faqs: defaultFaqs("journalism workshops"),
        relatedCategories: ["World", "Society", "Culture & Lifestyle"],
        relatedTopics: ["Journalism", "Media", "Public Affairs"],
        contentTypes: CONTENT_TYPES,
        trust: ["Workshop statistics", "Participant outcomes", "Editorial credentials"],
      },
      {
        slug: "memberships",
        name: "Memberships",
        icon: Wallet,
        headline: "Support independent public affairs journalism.",
        short: "Fund original research and reporting while accessing the IPN library.",
        value: "Support independent journalism and access the IPN library.",
        what: [
          "IPN Memberships fund original research, reporting and public affairs content while giving members access to the full IPN knowledge library.",
          "Membership supports the network's work on planet, people, progress and policies, and provides early access to research and member briefings.",
        ],
        audience: ["Supporters", "Researchers", "Professionals", "Students", "Organisations"],
        benefits: ["Access to IPN books, podcasts, infographics and reports", "Early access to research", "Member updates and briefings", "Community participation", "Support for independent journalism"],
        process: ["Choose Plan", "Subscribe", "Access Unlocked", "Enjoy Member Benefits"],
        pricing: "Recurring membership | see Gate Membership pricing",
        faqs: [
          { question: "What does an IPN membership include?", answer: "Membership unlocks premium IPN content and member benefits. All membership tiers are managed through the single Gate membership system." },
          ...defaultFaqs("memberships").slice(1),
        ],
        relatedCategories: ["World", "Politics & Governance", "Society"],
        relatedTopics: ["Global", "Membership", "Public Affairs"],
        contentTypes: CONTENT_TYPES,
      },
      {
        slug: "merchandise",
        name: "Merchandise",
        icon: ShoppingBag,
        headline: "Wear the values of the network.",
        short: "Official IPN-branded products for supporters and communities.",
        value: "Carry the network's identity and support its work.",
        what: [
          "IPN Merchandise lets supporters carry the network's identity with them through official branded products.",
          "Every purchase supports the editorial and research work of International Public Network.",
        ],
        audience: ["Supporters", "Community members", "Event attendees", "Journalism students"],
        benefits: ["Official IPN-branded products", "Quality materials", "Supports independent journalism", "Available across regions where shipping permits"],
        process: ["Browse", "Select Product", "Order", "Delivery"],
        pricing: "Product pricing at checkout",
        faqs: defaultFaqs("merchandise"),
        relatedCategories: ["Culture & Lifestyle", "World", "Society"],
        relatedTopics: ["Community", "Support", "Public Affairs"],
        contentTypes: CONTENT_TYPES,
      },
      {
        slug: "public-affairs-consulting",
        name: "Public Affairs Consulting",
        icon: Building2,
        headline: "Navigate policy, communication and public engagement.",
        short: "Strategic counsel for policy, stakeholder communication and advocacy.",
        value: "Strategic counsel for policy, communication and advocacy.",
        what: [
          "IPN Public Affairs Consulting supports organisations navigating public policy, stakeholder communication and advocacy.",
          "It combines editorial discipline with strategic counsel to help clients communicate with credibility and clarity across complex public environments.",
        ],
        audience: ["Corporates", "Non-profits", "Public bodies", "Advocacy groups", "International institutions"],
        benefits: ["Policy and stakeholder analysis", "Public communication strategy", "Positioning and messaging", "Crisis and reputational guidance", "Discreet, senior-level counsel"],
        process: DEFAULT_PROCESS,
        pricing: "Customised pricing",
        faqs: defaultFaqs("public affairs consulting"),
        relatedCategories: ["Politics & Governance", "Business & Economy", "Law & Justice"],
        relatedTopics: ["Policy", "Governance", "Public Affairs"],
        contentTypes: CONTENT_TYPES,
        trust: ["Consulting engagements", "Sector credentials", "Institutional clients"],
      },
      {
        slug: "research-reports",
        name: "Research Reports",
        icon: FileText,
        headline: "Original research on the issues shaping the world.",
        short: "Structured analysis across world affairs, politics, economy and society.",
        value: "Original analysis for decision-makers and researchers.",
        what: [
          "IPN Research Reports deliver original analysis across world affairs, politics, economy, environment and society.",
          "Each report combines structured analysis, evidence and clear executive summaries designed for decision-makers and researchers.",
        ],
        audience: ["Policy professionals", "Researchers", "Journalists", "Institutions", "Business decision-makers"],
        benefits: ["Original research and data", "Structured analysis", "Executive summaries", "Downloadable reports", "Editorial review standards"],
        process: ["Request Report", "Confirm Scope", "Research & Analysis", "Review Draft", "Delivery"],
        pricing: "Included with Gate Membership",
        faqs: defaultFaqs("research reports"),
        relatedCategories: ["World", "Politics & Governance", "Environment & Climate"],
        relatedTopics: ["Global", "Policy", "Research"],
        contentTypes: CONTENT_TYPES,
      },
    ],
  },
  {
    key: "IGC",
    slug: "igc",
    name: "Inspire Guide Connect",
    tagline: "Career, motivation, productivity and leadership growth.",
    focus: "Careers, productivity, leadership and professional development.",
    identity:
      "IGC is the professional growth arm of Gate, helping students, professionals and organisations build careers, leadership and sustainable productivity through books, podcasts, infographics and workshops.",
    website: "https://www.drzaydalhaji.com",
    whatsapp: WHATSAPP,
    categories: [
      "Career Development",
      "Motivation",
      "Leadership & Growth Mindset",
      "Productivity & Time Management",
      "Business & Entrepreneurship",
      "Communication & Public Speaking Skills",
      "Environmental Sustainability",
    ],
    socials: [
      { label: "Website", url: "https://www.drzaydalhaji.com", icon: Globe },
      { label: "YouTube", url: "https://www.youtube.com/channel/UCmosGR6TUcZvjeq3zL7hgwA", icon: Youtube },
      { label: "Spotify", url: "https://open.spotify.com/show/7goWWp28Ljd7BC5K3Bh4Bb", icon: Music2 },
      { label: "Apple Podcasts", url: "https://podcasts.apple.com/in/podcast/igc-gate/id1844060493", icon: Podcast },
      { label: "Instagram", url: "https://www.instagram.com/igc.gate/", icon: Instagram },
      { label: "Facebook", url: "https://www.facebook.com/igc.gates/", icon: Facebook },
      { label: "LinkedIn", url: "https://www.linkedin.com/company/igcgate/", icon: Linkedin },
      { label: "X", url: "https://x.com/igcgate", icon: Twitter },
      { label: "Students Community", url: "https://teams.live.com/l/community/FEA6f9LrCDRcmvcagI", icon: Users },
      { label: "Professionals Community", url: "https://teams.live.com/l/community/FEAEDqxaBj-1KkcWgI", icon: Users },
      { label: "Corporate Community", url: "https://teams.live.com/l/community/FEAhzDO4OThcgh5WwI", icon: Users },
      { label: "WhatsApp Contact", url: WHATSAPP, icon: MessageCircle },
    ],
    services: [
      {
        slug: "management-consulting",
        name: "Management Consulting",
        icon: Building2,
        headline: "Grow people and organisations with clarity.",
        short: "Align leadership, productivity and culture with structured counsel.",
        value: "Align leadership, productivity and culture.",
        what: [
          "IGC Management Consulting helps organisations align leadership, productivity and culture.",
          "We work with teams to define priorities, improve communication and build habits that compound over time, with follow-through support after recommendations are delivered.",
        ],
        audience: ["Founders and CEOs", "Team leaders", "HR and L&D teams", "Startups and SMEs", "Corporate departments"],
        benefits: ["Leadership and team diagnosis", "Productivity frameworks", "Communication improvement plans", "Workshop facilitation", "Follow-through support"],
        process: DEFAULT_PROCESS,
        pricing: "Customised pricing",
        faqs: defaultFaqs("management consulting"),
        relatedCategories: ["Leadership & Growth Mindset", "Business & Entrepreneurship", "Productivity & Time Management"],
        relatedTopics: ["Leadership", "Culture", "Performance"],
        contentTypes: CONTENT_TYPES,
        trust: ["Consulting engagements", "Organisation outcomes"],
      },
      {
        slug: "career-employability-workshops",
        name: "Career & Employability Live Online/Offline Workshops",
        icon: GraduationCap,
        headline: "Build the skills employers actually look for.",
        short: "Practical preparation for CVs, interviews and the working world.",
        value: "Build the skills employers actually look for.",
        what: [
          "IGC Career & Employability Workshops help students, graduates and professionals build employability, from CVs and interviews to personal branding and workplace readiness.",
          "Each workshop is practical and interactive, delivered live online and in person for universities, colleges and career programmes.",
        ],
        audience: ["Students", "Graduates", "Early-career professionals", "Career changers", "Universities and colleges"],
        benefits: ["CV and interview preparation", "Personal branding", "Workplace communication", "Live online and offline formats", "Certificate of participation"],
        process: ["Enquire", "Choose Format", "Receive Curriculum", "Attend Sessions", "Certificate & Follow-up"],
        pricing: "Customised pricing",
        faqs: defaultFaqs("career and employability workshops"),
        relatedCategories: ["Career Development", "Communication & Public Speaking Skills", "Motivation"],
        relatedTopics: ["Employability", "Career", "Communication"],
        contentTypes: CONTENT_TYPES,
        trust: ["Workshop statistics", "Participant outcomes"],
      },
      {
        slug: "productivity-time-management-workshops",
        name: "Productivity & Time Management Live Online/Offline Workshops",
        icon: Timer,
        headline: "Do meaningful work in the time you have.",
        short: "Attention, prioritisation and sustainable systems for busy professionals.",
        value: "Do meaningful work in the time you have.",
        what: [
          "IGC Productivity & Time Management Workshops are built around attention, prioritisation and sustainable systems.",
          "Participants learn practical methods to manage time, reduce overwhelm and protect energy for what matters most.",
        ],
        audience: ["Professionals", "Students", "Entrepreneurs", "Team managers", "Anyone rebuilding their routines"],
        benefits: ["Prioritisation frameworks", "Time-blocking systems", "Attention management", "Habit and energy planning", "Live online and offline formats"],
        process: ["Enquire", "Choose Format", "Receive Curriculum", "Attend Sessions", "Certificate & Follow-up"],
        pricing: "Customised pricing",
        faqs: defaultFaqs("productivity workshops"),
        relatedCategories: ["Productivity & Time Management", "Career Development", "Leadership & Growth Mindset"],
        relatedTopics: ["Productivity", "Time Management", "Habits"],
        contentTypes: CONTENT_TYPES,
      },
      {
        slug: "books",
        name: "Books",
        icon: BookOpen,
        headline: "Read work worth returning to.",
        short: "Practical books on careers, motivation, leadership and productivity.",
        value: "Practical reading for careers and leadership.",
        what: [
          "IGC Books cover career development, motivation, leadership and productivity.",
          "Each title is written to be practical, readable and useful in daily working life, with companion resources where available.",
        ],
        audience: ["Professionals", "Students", "Leaders", "Lifelong learners"],
        benefits: ["Practical, readable content", "Career and leadership focus", "Print and digital formats", "Companion resources where available"],
        process: ["Browse Catalogue", "Purchase", "Read & Apply"],
        pricing: "Retail pricing at point of purchase",
        faqs: defaultFaqs("IGC books"),
        relatedCategories: ["Motivation", "Leadership & Growth Mindset", "Business & Entrepreneurship"],
        relatedTopics: ["Reading", "Growth", "Career"],
        contentTypes: CONTENT_TYPES,
      },
      {
        slug: "memberships",
        name: "Memberships",
        icon: Wallet,
        headline: "Learn with a community that grows with you.",
        short: "Support IGC's work and access its full knowledge library.",
        value: "Learn with a community that grows with you.",
        what: [
          "IGC Memberships support the network's work on careers, productivity and leadership while giving members access to IGC books, podcasts, infographics and workshops.",
          "Membership is managed through the single Gate membership system, with the same benefits across all four hubs.",
        ],
        audience: ["Students", "Professionals", "Leaders", "Lifelong learners"],
        benefits: ["Access to IGC books, podcasts, infographics and reports", "Workshop access", "Member community", "Learning progress tracking", "Support for accessible growth resources"],
        process: ["Choose Plan", "Subscribe", "Access Unlocked", "Enjoy Member Benefits"],
        pricing: "Recurring membership | see Gate Membership pricing",
        faqs: [
          { question: "What does an IGC membership include?", answer: "Membership unlocks premium IGC content and member benefits through the single Gate membership system." },
          ...defaultFaqs("memberships").slice(1),
        ],
        relatedCategories: ["Career Development", "Motivation", "Leadership & Growth Mindset"],
        relatedTopics: ["Membership", "Career", "Growth"],
        contentTypes: CONTENT_TYPES,
      },
      {
        slug: "patrons-donations",
        name: "Patrons & Donations",
        icon: HeartHandshake,
        headline: "Help make growth resources accessible.",
        short: "Fund workshops, scholarships and public learning materials.",
        value: "Help make growth resources accessible.",
        what: [
          "Patron support funds IGC's mission to make career and productivity resources accessible to students and communities.",
          "Donations support workshops, scholarships and public learning materials that would otherwise be out of reach.",
        ],
        audience: ["Patrons", "Philanthropists", "Alumni", "Community supporters"],
        benefits: ["Funding workshops and scholarships", "Access to patron updates", "Recognition options", "Direct impact on learners"],
        process: ["Choose Patron Tier", "Donate", "Impact Reporting"],
        pricing: "Open donation and patron tiers",
        faqs: defaultFaqs("patron support"),
        relatedCategories: ["Motivation", "Career Development", "Environmental Sustainability"],
        relatedTopics: ["Community", "Access", "Impact"],
        contentTypes: CONTENT_TYPES,
      },
    ],
  },
  {
    key: "IFR",
    slug: "ifr",
    name: "Integrity Finance Research",
    tagline: "Ethical finance, markets, literacy and economic research.",
    focus: "Finance, economics, research and financial literacy.",
    identity:
      "IFR is the finance and research arm of Gate, examining ethical finance, banking governance, economics and market dynamics through books, podcasts, infographics and structured research reports.",
    website: "https://www.zaydhaji.com",
    whatsapp: WHATSAPP,
    categories: [
      "Ethical Finance",
      "Ethical Banking",
      "Shariah Governance",
      "Economics",
      "Indian Economy",
      "Global Economy",
      "Industry Analysis",
      "Company Research",
      "Financial Markets",
      "Public Policy",
      "Financial Literacy",
    ],
    socials: [
      { label: "Website", url: "https://www.zaydhaji.com", icon: Globe },
      { label: "YouTube", url: "https://www.youtube.com/channel/UCbupKTwiuJV-zOTvDGZvZrg", icon: Youtube },
      { label: "Spotify", url: "https://open.spotify.com/show/7G5AbdkS2N3d2BBj0RDmuz?si=fd0ff4ce050a4573", icon: Music2 },
      { label: "Apple Podcasts", url: "https://podcasts.apple.com/in/podcast/islamic-finance-research/id1717593002", icon: Podcast },
      { label: "Instagram", url: "https://www.instagram.com/ifr.gate/", icon: Instagram },
      { label: "Facebook", url: "https://www.facebook.com/ifr.gate/", icon: Facebook },
      { label: "LinkedIn", url: "https://www.linkedin.com/company/ifrgate/", icon: Linkedin },
      { label: "X", url: "https://x.com/ifrgate", icon: Twitter },
      { label: "Microsoft Teams", url: "https://teams.live.com/l/community/FEAbFbMvQrnZwzE4QI?v=g1", icon: Users },
      { label: "WhatsApp Contact", url: WHATSAPP, icon: MessageCircle },
    ],
    services: [
      {
        slug: "research-reports",
        name: "Research Reports",
        icon: FileText,
        headline: "Finance research that holds itself to a higher standard.",
        short: "Structured research on ethical finance, economics and market dynamics.",
        value: "Finance research held to a higher standard.",
        what: [
          "IFR Research Reports examine ethical finance, banking governance, economics and market dynamics with a focus on integrity.",
          "Each report is structured, evidenced and written for decision-makers and researchers who value rigour over noise.",
        ],
        audience: ["Finance professionals", "Researchers", "Regulators", "Institutions", "Ethical investors"],
        benefits: ["Original research and evidence", "Ethical finance frameworks", "Executive summaries", "Downloadable reports", "Governance and policy analysis"],
        process: ["Request Report", "Confirm Scope", "Research & Analysis", "Review Draft", "Delivery"],
        pricing: "Included with Gate Membership",
        faqs: defaultFaqs("research reports"),
        relatedCategories: ["Ethical Finance", "Ethical Banking", "Financial Markets"],
        relatedTopics: ["Finance", "Research", "Governance"],
        contentTypes: CONTENT_TYPES,
      },
      {
        slug: "books",
        name: "Books",
        icon: BookOpen,
        headline: "Understand finance with integrity.",
        short: "Clear, structured books on ethical finance and financial literacy.",
        value: "Understand finance with integrity.",
        what: [
          "IFR Books translate complex financial and economic ideas into clear, structured knowledge, from ethical banking and Shariah governance to financial literacy.",
          "They are written for learners and practitioners who want depth without unnecessary jargon.",
        ],
        audience: ["Finance learners", "Practitioners", "Students", "Researchers"],
        benefits: ["Clear, structured content", "Ethical and governance focus", "Print and digital formats", "Financial literacy resources"],
        process: ["Browse Catalogue", "Purchase", "Read & Apply"],
        pricing: "Retail pricing at point of purchase",
        faqs: defaultFaqs("IFR books"),
        relatedCategories: ["Financial Literacy", "Economics", "Ethical Finance"],
        relatedTopics: ["Finance", "Literacy", "Ethics"],
        contentTypes: CONTENT_TYPES,
      },
      {
        slug: "memberships",
        name: "Memberships",
        icon: Wallet,
        headline: "Access finance research built on integrity.",
        short: "Support independent research and access the full IFR library.",
        value: "Access research built on integrity.",
        what: [
          "IFR Memberships support independent finance research and grant access to IFR books, reports, podcasts and literacy workshops.",
          "Membership is managed through the single Gate membership system with identical benefits across the four hubs.",
        ],
        audience: ["Finance professionals", "Researchers", "Students", "Institutions"],
        benefits: ["Access to IFR books, reports, podcasts and infographics", "Literacy workshop access", "Member briefings", "Learning progress tracking", "Support for independent research"],
        process: ["Choose Plan", "Subscribe", "Access Unlocked", "Enjoy Member Benefits"],
        pricing: "Recurring membership | see Gate Membership pricing",
        faqs: [
          { question: "What does an IFR membership include?", answer: "Membership unlocks premium IFR content and member benefits through the single Gate membership system." },
          ...defaultFaqs("memberships").slice(1),
        ],
        relatedCategories: ["Ethical Finance", "Economics", "Financial Markets"],
        relatedTopics: ["Finance", "Membership", "Research"],
        contentTypes: CONTENT_TYPES,
      },
      {
        slug: "financial-literacy-workshops",
        name: "Financial Literacy Live Online/Offline Workshops",
        icon: Wallet,
        headline: "Make informed financial decisions with confidence.",
        short: "Practical workshops on money management and ethical finance basics.",
        value: "Make informed money decisions with confidence.",
        what: [
          "IFR Financial Literacy Workshops build everyday financial literacy, from budgeting and saving to understanding credit, risk and ethical investment choices.",
          "Sessions are practical, delivered live online and in person for individuals, community organisations and corporate teams.",
        ],
        audience: ["Individuals", "Students", "Families", "Community organisations", "Corporate teams"],
        benefits: ["Practical money management", "Ethical finance principles", "Live online and offline formats", "Certificate of participation"],
        process: ["Enquire", "Choose Format", "Receive Curriculum", "Attend Sessions", "Certificate & Follow-up"],
        pricing: "Customised pricing",
        faqs: defaultFaqs("financial literacy workshops"),
        relatedCategories: ["Financial Literacy", "Ethical Finance", "Economics"],
        relatedTopics: ["Literacy", "Personal Finance", "Ethics"],
        contentTypes: CONTENT_TYPES,
        trust: ["Workshop statistics", "Participant outcomes"],
      },
      {
        slug: "patrons-donations",
        name: "Patrons & Donations",
        icon: HeartHandshake,
        headline: "Support finance research the public can trust.",
        short: "Fund independent research on ethical finance and literacy.",
        value: "Support finance research the public can trust.",
        what: [
          "Patron support funds independent research on ethical finance and literacy, keeping knowledge accessible beyond paywalls.",
          "Donations sustain research projects, reports and public financial literacy materials.",
        ],
        audience: ["Patrons", "Philanthropists", "Institutions", "Community supporters"],
        benefits: ["Funding independent research", "Access to research updates", "Recognition options", "Direct impact on financial literacy"],
        process: ["Choose Patron Tier", "Donate", "Impact Reporting"],
        pricing: "Open donation and patron tiers",
        faqs: defaultFaqs("patron support"),
        relatedCategories: ["Ethical Finance", "Financial Literacy", "Public Policy"],
        relatedTopics: ["Research", "Access", "Impact"],
        contentTypes: CONTENT_TYPES,
      },
    ],
  },
  {
    key: "ISR",
    slug: "isr",
    name: "Ideological Studies Research",
    tagline: "Quran, Hadith, theology, ethics and contemporary issues.",
    focus: "Theological and ideological research.",
    identity:
      "ISR is the theological research arm of Gate, engaging Quranic studies, Hadith methodology, creed, ethics and contemporary questions with scholarly discipline through books, podcasts, infographics and research.",
    website: "https://www.zaydalhaji.com",
    whatsapp: WHATSAPP,
    categories: [
      "Quranic Studies (6,236 Verses)",
      "Tafsir Ibn Kathir (6,236 Verses)",
      "Hadith Studies (68,061 Hadiths)",
      "Sahih Bukhari (7,563 Hadiths)",
      "Sahih Muslim (7,563 Hadiths)",
      "Sunan Abu Dawud (5,274 Hadiths)",
      "Jami at Tirmidhi (3,956 Hadiths)",
      "Sunan an Nasai (5,758 Hadiths)",
      "Sunan Ibn Majah (4,341 Hadiths)",
      "Al Muwatta by Imam Malik (1,861 Hadiths)",
      "Musnad Ahmad ibn Hanbal (28,199 Hadiths)",
      "Sunan ad Darimi (3,546 Hadiths)",
      "Creed and Theology",
      "Theological Jurisprudence",
      "Theological History",
      "Theological Ethics",
      "Science and Theology",
      "Feminism and Theology",
      "Terrorism and Theology",
      "Relationships and Theology",
      "Prophetic and Companion Biographies",
      "Contemporary Theological Issues",
    ],
    socials: [
      { label: "Website", url: "https://www.zaydalhaji.com", icon: Globe },
      { label: "YouTube", url: "https://www.youtube.com/channel/UCnZzzKF9lPSvnH6-oduHTjw", icon: Youtube },
      { label: "Spotify", url: "https://open.spotify.com/show/5rF294PWY9uvktx4JD4BTv?si=XXGix1EVS-GT3CXl9RoUMw", icon: Music2 },
      { label: "Apple Podcasts", url: "https://podcasts.apple.com/in/podcast/ideological-studies-research/id1740407474", icon: Podcast },
      { label: "Instagram", url: "https://www.instagram.com/isr.gate/", icon: Instagram },
      { label: "Facebook", url: "https://www.facebook.com/isr.gate/", icon: Facebook },
      { label: "LinkedIn", url: "https://www.linkedin.com/company/isrgate/", icon: Linkedin },
      { label: "X", url: "https://x.com/isrgate", icon: Twitter },
      { label: "Microsoft Teams", url: "https://teams.live.com/l/community/FEACV71antVJvm6NQI?v=g1", icon: Users },
      { label: "WhatsApp Contact", url: WHATSAPP, icon: MessageCircle },
    ],
    services: [
      {
        slug: "research-reports",
        name: "Research Reports",
        icon: FileText,
        headline: "Rigorous research grounded in classical sources.",
        short: "Referenced research on Quran, Hadith, theology and ideology.",
        value: "Rigorous research grounded in classical sources.",
        what: [
          "ISR Research Reports explore Quranic studies, Hadith methodology, theology and contemporary ideological questions with scholarly discipline.",
          "Each report is referenced, structured and written for researchers, educators and institutions that value precision.",
        ],
        audience: ["Students", "Researchers", "Educators", "Institutions", "Religious scholars"],
        benefits: ["Original referenced research", "Classical source engagement", "Structured analysis", "Executive summaries", "Downloadable reports"],
        process: ["Request Report", "Confirm Scope", "Research & Analysis", "Review Draft", "Delivery"],
        pricing: "Included with Gate Membership",
        faqs: defaultFaqs("research reports"),
        relatedCategories: ["Creed and Theology", "Contemporary Theological Issues", "Theological Ethics"],
        relatedTopics: ["Theology", "Research", "Ethics"],
        contentTypes: CONTENT_TYPES,
      },
      {
        slug: "books",
        name: "Books",
        icon: BookOpen,
        headline: "Books that serve serious study.",
        short: "Structured books on Quranic studies, Hadith and theology.",
        value: "Books that serve serious study.",
        what: [
          "ISR Books cover Quranic studies, Hadith sciences, creed, theology and contemporary questions.",
          "They are designed for students and researchers who value depth and accuracy, with classical references and structured presentation.",
        ],
        audience: ["Students", "Researchers", "Educators", "Institutions"],
        benefits: ["Scholar-aligned content", "Classical references", "Structured presentation", "Print and digital formats"],
        process: ["Browse Catalogue", "Purchase", "Read & Study"],
        pricing: "Retail pricing at point of purchase",
        faqs: defaultFaqs("ISR books"),
        relatedCategories: ["Quranic Studies (6,236 Verses)", "Hadith Studies (68,061 Hadiths)", "Creed and Theology"],
        relatedTopics: ["Quran", "Hadith", "Theology"],
        contentTypes: CONTENT_TYPES,
      },
      {
        slug: "memberships",
        name: "Memberships",
        icon: Wallet,
        headline: "Sustain research that takes ideas seriously.",
        short: "Support theological research and access the full ISR library.",
        value: "Sustain research that takes ideas seriously.",
        what: [
          "ISR Memberships support ideological and theological research and provide access to ISR books, reports, podcasts and workshops.",
          "Membership is managed through the single Gate membership system with identical benefits across all four hubs.",
        ],
        audience: ["Students", "Researchers", "Educators", "Institutions"],
        benefits: ["Access to ISR books, reports, podcasts and infographics", "Workshop access", "Research updates", "Learning progress tracking", "Support for serious scholarship"],
        process: ["Choose Plan", "Subscribe", "Access Unlocked", "Enjoy Member Benefits"],
        pricing: "Recurring membership | see Gate Membership pricing",
        faqs: [
          { question: "What does an ISR membership include?", answer: "Membership unlocks premium ISR content and member benefits through the single Gate membership system." },
          ...defaultFaqs("memberships").slice(1),
        ],
        relatedCategories: ["Creed and Theology", "Contemporary Theological Issues", "Quranic Studies (6,236 Verses)"],
        relatedTopics: ["Theology", "Membership", "Research"],
        contentTypes: CONTENT_TYPES,
      },
      {
        slug: "theological-workshops",
        name: "Theological Live Online/Offline Workshops",
        icon: Landmark,
        headline: "Study theology with structure and discipline.",
        short: "Structured workshops on creed, ethics and contemporary theological issues.",
        value: "Study theology with structure and discipline.",
        what: [
          "ISR Theological Workshops offer structured study of creed, jurisprudence, ethics and contemporary theological issues.",
          "Delivered live online and in person, they are designed for students, researchers, educators and institutions who want serious, structured engagement with classical and contemporary sources.",
        ],
        audience: ["Students", "Researchers", "Educators", "Professionals", "Institutions"],
        benefits: ["Structured curriculum", "Primary source engagement", "Live online and offline formats", "Certificate of participation", "Small-group discussion"],
        process: ["Enquire", "Choose Format", "Receive Curriculum", "Attend Sessions", "Certificate & Follow-up"],
        pricing: "Customised pricing",
        faqs: defaultFaqs("theological workshops"),
        relatedCategories: ["Creed and Theology", "Theological Jurisprudence", "Contemporary Theological Issues"],
        relatedTopics: ["Theology", "Ethics", "Scholarship"],
        contentTypes: CONTENT_TYPES,
        trust: ["Workshop statistics", "Participant outcomes", "Scholarly credentials"],
      },
      {
        slug: "patrons-donations",
        name: "Patrons and Donations",
        icon: HeartHandshake,
        headline: "Help knowledge remain open.",
        short: "Fund research, translation and publication work.",
        value: "Help knowledge remain open.",
        what: [
          "Patron support funds ISR research, translation and publication work, keeping theological scholarship accessible to serious learners.",
          "Donations support the production and dissemination of research that would otherwise remain inaccessible.",
        ],
        audience: ["Patrons", "Philanthropists", "Institutions", "Community supporters"],
        benefits: ["Funding research and publication", "Access to research updates", "Recognition options", "Direct impact on scholarship"],
        process: ["Choose Patron Tier", "Donate", "Impact Reporting"],
        pricing: "Open donation and patron tiers",
        faqs: defaultFaqs("patron support"),
        relatedCategories: ["Creed and Theology", "Theological Ethics", "Contemporary Theological Issues"],
        relatedTopics: ["Scholarship", "Access", "Impact"],
        contentTypes: CONTENT_TYPES,
      },
    ],
  },
];

export const hubByKey = (key: HubKey): GateHub => hubs.find((h) => h.key === key) as GateHub;
export const hubBySlug = (slug: string): GateHub | undefined => hubs.find((h) => h.slug === slug);
export const serviceBySlug = (hub: GateHub, slug: string): GateService | undefined =>
  hub.services.find((s) => s.slug === slug);
